// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJfLRn_8u86HzQeEIzuoUF7w1bjnwFjD0',
    appId: '1:1063835746128:web:7662742daa141b1e163655',
    messagingSenderId: '1063835746128',
    projectId: 'p2mobdev',
    authDomain: 'p2mobdev.firebaseapp.com',
    storageBucket: 'p2mobdev.appspot.com',
    measurementId: 'G-FQD07BJHYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1vkAFE6E1c2-_8eanZQl7ZUiCmzVZrc',
    appId: '1:1063835746128:android:e3f23b0a032c757e163655',
    messagingSenderId: '1063835746128',
    projectId: 'p2mobdev',
    storageBucket: 'p2mobdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39-d3rkvhzSuvW2jOUTYMOc6kAqa2yBM',
    appId: '1:1063835746128:ios:16af796f32ebd5d8163655',
    messagingSenderId: '1063835746128',
    projectId: 'p2mobdev',
    storageBucket: 'p2mobdev.appspot.com',
    iosClientId: '1063835746128-roraoi21rmim4dpa8pcjlp2hbm0ji8em.apps.googleusercontent.com',
    iosBundleId: 'com.example.p1MobDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39-d3rkvhzSuvW2jOUTYMOc6kAqa2yBM',
    appId: '1:1063835746128:ios:16af796f32ebd5d8163655',
    messagingSenderId: '1063835746128',
    projectId: 'p2mobdev',
    storageBucket: 'p2mobdev.appspot.com',
    iosClientId: '1063835746128-roraoi21rmim4dpa8pcjlp2hbm0ji8em.apps.googleusercontent.com',
    iosBundleId: 'com.example.p1MobDev',
  );
}
